apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

namespace: prod-coffeeshop

patches:
- ./deployment-patches.yaml
- ./route-patches.yaml
- ./service-patches.yaml

configMapGenerator:
- envs:
  - ./configmap.env
  name: coffee-shop
